### ISSUE TITLE
'zookeeper_hosts' is undefined

### ISSUE THREAD

**Issue by jaetask** [hpcloud-mon/ansible-kafka#3]
Hi,

Thanks for creating this module. I am trying to use it and am getting the following error. Is there a dependency that I am not aware of?

TASK: [tkuhlman.kafka | create server.properties] ***************************** 
fatal: [vagrant1] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'zookeeper_hosts' is undefined", 'failed': True}
fatal: [vagrant1] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'zookeeper_hosts' is undefined", 'failed': True}

FATAL: all hosts have already failed -- aborting

**Comment by tkuhlman** [comment]
Looks like zookeeper_hosts env variable is not defined. This must be defined. I mention it and the other important env variables in the readme.
